#!/usr/bin/env bash
# display Best School 10 time

C=1
while [ $C -lt 11 ]
do
    if [ $C = 4 ]
    then
        echo "bad luck"
    elif [ $C = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    let C+=1
done
